# Generated by Django 6.0.4 on 2026-04-14 00:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('nominees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('paystack', 'Paystack')], default='paystack', max_length=24)),
                ('status', models.CharField(choices=[('initialized', 'Initialized'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='initialized', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('vote_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('voter_name', models.CharField(blank=True, max_length=120)),
                ('voter_email', models.EmailField(blank=True, max_length=254)),
                ('voter_phone', models.CharField(blank=True, max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('gateway_reference', models.CharField(max_length=100, unique=True)),
                ('gateway_access_code', models.CharField(blank=True, max_length=120)),
                ('gateway_checkout_url', models.URLField(blank=True)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('webhook_payload', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_webhook_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='events.event')),
                ('nominee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='nominees.nominee')),
            ],
            options={
                'ordering': ('-initiated_at',),
            },
        ),
    ]
