# Generated by Django 6.0.4 on 2026-06-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_evt_owner_kind_stat_start_and_more'),
        ('nominees', '0001_initial'),
        ('payments', '0002_paymentattempt_callback_received_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['event', 'status', '-initiated_at'], name='pay_event_status_init'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['event', 'nominee', 'status'], name='pay_event_nom_status'),
        ),
    ]
