# Generated by Django 6.0.4 on 2026-06-02 21:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def backfill_payment_attempt_commission(apps, schema_editor):
    PaymentAttempt = apps.get_model('payments', 'PaymentAttempt')
    for attempt in PaymentAttempt.objects.select_related('event').filter(
        platform_commission_percent__isnull=True,
        event__platform_commission_percent__isnull=False,
    ):
        attempt.platform_commission_percent = attempt.event.platform_commission_percent
        attempt.save(update_fields=['platform_commission_percent'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_platform_commission_percent_and_more'),
        ('payments', '0003_paymentattempt_pay_event_status_init_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentattempt',
            name='platform_commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.RunPython(backfill_payment_attempt_commission, noop_reverse),
    ]
