# Generated by Django 6.0.4 on 2026-04-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_leaderboard',
            field=models.BooleanField(default=True),
        ),
    ]
