# Generated by Django 6.0.4 on 2026-05-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_show_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='flyer',
            field=models.ImageField(blank=True, upload_to='events/flyers/'),
        ),
    ]
