# Generated by Django 6.0.4 on 2026-05-31 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_flyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='kind',
            field=models.CharField(choices=[('paid_competition', 'Paid competition'), ('secure_election', 'Secure election')], default='paid_competition', max_length=24),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('configured', 'Configured'), ('roster_uploaded', 'Roster uploaded'), ('priced', 'Priced'), ('payment_pending', 'Payment pending'), ('paid', 'Paid'), ('roster_locked', 'Roster locked'), ('credentials_issued', 'Credentials issued'), ('ready', 'Ready'), ('open', 'Open'), ('published', 'Published'), ('closed', 'Closed'), ('tallied', 'Tallied'), ('certified', 'Certified'), ('archived', 'Archived'), ('cancelled', 'Cancelled')], default='draft', max_length=24),
        ),
    ]
