# Generated by Django 6.0.4 on 2026-06-01 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_kind_alter_event_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['owner', 'kind', 'status', 'start_at'], name='evt_owner_kind_stat_start'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['owner', 'kind', '-created_at'], name='evt_owner_kind_created'),
        ),
    ]
