# Generated by Django 6.0.4 on 2026-06-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_evt_owner_kind_stat_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=32)),
                (
                    'heard_about_us',
                    models.CharField(
                        choices=[
                            ('social_media', 'Social media'),
                            ('friend_referral', 'Friend referral'),
                            ('campus_event', 'Campus event'),
                            ('organization_referral', 'Organization referral'),
                            ('google_search', 'Google search'),
                            ('whatsapp', 'WhatsApp'),
                            ('other', 'Other'),
                        ],
                        max_length=32,
                    ),
                ),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
