# Generated by Django 6.0.4 on 2026-06-02 21:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_event_commission(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    default_percent = (getattr(settings, 'PLATFORM_COMMISSION_RATE', Decimal('0.10')) * Decimal('100')).quantize(
        Decimal('0.01')
    )
    Event.objects.filter(
        kind='paid_competition',
        platform_commission_percent__isnull=True,
    ).update(platform_commission_percent=default_percent)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_allow_public_nominations_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='platform_commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Commission percentage retained by Vootely for this paid competition.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AddField(
            model_name='event',
            name='platform_commission_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='platform_commission_set_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configured_event_commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_event_commission, noop_reverse),
    ]
