# Generated by Django 6.0.4 on 2026-06-06 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_platform_commission_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Number of votes included in this package.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Total price for this package in event currency.', max_digits=10)),
                ('label', models.CharField(blank=True, help_text='Optional badge label (e.g. Save 10%, Popular).', max_length=80)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this package is active and selectable.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_bundles', to='events.event')),
            ],
            options={
                'ordering': ('quantity',),
                'unique_together': {('event', 'quantity')},
            },
        ),
    ]
