# Generated by Django 6.0.4 on 2026-06-06 12:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_votebundle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('7.00'), help_text='Commission percentage retained by Vootely for paid ticket sales.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_commission_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_commission_set_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configured_ticket_commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='kind',
            field=models.CharField(choices=[('paid_competition', 'Paid competition'), ('secure_election', 'Secure election'), ('ticketed_event', 'Ticketed event')], default='paid_competition', max_length=24),
        ),
    ]
