# Generated by Codex on 2026-06-06

import hashlib

from django.db import migrations, models


PUBLIC_CODE_ALPHABET = '23456789ABCDEFGHJKLMNPQRSTUVWXYZ'
PUBLIC_CODE_LENGTH = 5


def deterministic_public_code(event, counter=0):
    seed = f'{event.pk}:{event.slug}:{event.created_at.isoformat()}:{counter}'.encode('utf-8')
    value = int.from_bytes(hashlib.sha256(seed).digest()[:8], 'big')
    chars = []
    for _idx in range(PUBLIC_CODE_LENGTH):
        value, remainder = divmod(value, len(PUBLIC_CODE_ALPHABET))
        chars.append(PUBLIC_CODE_ALPHABET[remainder])
    return f"V-{''.join(chars)}"


def backfill_public_codes(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    for event in Event.objects.order_by('id'):
        if event.public_code:
            continue
        counter = 0
        code = deterministic_public_code(event, counter)
        while Event.objects.exclude(pk=event.pk).filter(public_code=code).exists():
            counter += 1
            code = deterministic_public_code(event, counter)
        event.public_code = code
        event.save(update_fields=['public_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_ticket_commission_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='public_code',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True, unique=True),
        ),
        migrations.RunPython(backfill_public_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='event',
            name='public_code',
            field=models.CharField(blank=True, db_index=True, max_length=16, unique=True),
        ),
    ]
