# Generated by Codex on 2026-06-07

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


USSD_CODE_MIN = 10
USSD_CODE_MAX = 999


def backfill_ussd_codes(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    next_code = USSD_CODE_MIN
    used_codes = set(
        Event.objects.exclude(ussd_code__isnull=True).values_list('ussd_code', flat=True)
    )
    for event in Event.objects.order_by('id'):
        if event.ussd_code:
            continue
        while next_code in used_codes and next_code <= USSD_CODE_MAX:
            next_code += 1
        if next_code > USSD_CODE_MAX:
            raise RuntimeError('Not enough USSD codes available between 10 and 999.')
        event.ussd_code = next_code
        event.save(update_fields=['ussd_code'])
        used_codes.add(next_code)
        next_code += 1


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_event_date_event_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ussd_code',
            field=models.PositiveSmallIntegerField(
                blank=True,
                db_index=True,
                null=True,
                unique=True,
                validators=[MinValueValidator(10), MaxValueValidator(999)],
            ),
        ),
        migrations.RunPython(backfill_ussd_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='event',
            name='ussd_code',
            field=models.PositiveSmallIntegerField(
                blank=True,
                db_index=True,
                unique=True,
                validators=[MinValueValidator(10), MaxValueValidator(999)],
            ),
        ),
    ]
