# Generated by Django 6.0.4 on 2026-06-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_event_owner'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contactinquiry',
            index=models.Index(fields=['-created_at'], name='contact_inquiry_created'),
        ),
    ]
