# Generated by Django 6.0.4 on 2026-06-06 12:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0010_event_ticket_commission_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quantity_available', models.PositiveIntegerField()),
                ('sale_start_at', models.DateTimeField()),
                ('sale_end_at', models.DateTimeField()),
                ('max_per_order', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.event')),
            ],
            options={
                'ordering': ('price', 'name'),
            },
        ),
        migrations.CreateModel(
            name='TicketPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('paystack', 'Paystack')], default='paystack', max_length=24)),
                ('status', models.CharField(choices=[('initialized', 'Initialized'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='initialized', max_length=16)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('ticket_commission_percent', models.DecimalField(decimal_places=2, default=Decimal('7.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('buyer_name', models.CharField(blank=True, max_length=120)),
                ('buyer_email', models.EmailField(blank=True, max_length=254)),
                ('buyer_phone', models.CharField(blank=True, max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('gateway_reference', models.CharField(max_length=100, unique=True)),
                ('gateway_access_code', models.CharField(blank=True, max_length=120)),
                ('gateway_checkout_url', models.URLField(blank=True)),
                ('gateway_status', models.CharField(blank=True, max_length=32)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('webhook_payload', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('callback_received_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_webhook_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_purchases', to='events.event')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='ticketing.tickettype')),
            ],
            options={
                'ordering': ('-initiated_at',),
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=32, unique=True)),
                ('qr_data', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_tickets', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='events.event')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='ticketing.ticketpurchase')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='ticketing.tickettype')),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='TicketCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('scanner_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('scanner_user_agent', models.TextField(blank=True)),
                ('status_before', models.CharField(blank=True, max_length=16)),
                ('status_after', models.CharField(blank=True, max_length=16)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_checkins', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_checkins', to='events.event')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkins', to='ticketing.ticket')),
            ],
            options={
                'ordering': ('-scanned_at',),
                'indexes': [models.Index(fields=['event', '-scanned_at'], name='checkin_event_scanned'), models.Index(fields=['ticket', '-scanned_at'], name='checkin_ticket_scanned')],
            },
        ),
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['event', 'is_active', 'sale_start_at', 'sale_end_at'], name='tt_event_active_sale'),
        ),
        migrations.AddConstraint(
            model_name='tickettype',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='ticket_type_event_name_unique'),
        ),
        migrations.AddIndex(
            model_name='ticketpurchase',
            index=models.Index(fields=['event', 'status', '-initiated_at'], name='tp_event_status_init'),
        ),
        migrations.AddIndex(
            model_name='ticketpurchase',
            index=models.Index(fields=['ticket_type', 'status'], name='tp_type_status'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['event', 'status'], name='ticket_event_status'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['purchase', 'status'], name='ticket_purchase_status'),
        ),
    ]
