# Generated by Codex on 2026-06-07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_public_code'),
        ('ticketing', '0002_alter_tickettype_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketScannerPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_name', models.CharField(max_length=80)),
                ('staff_label', models.CharField(blank=True, max_length=120)),
                ('token', models.CharField(blank=True, max_length=64, unique=True)),
                ('pin_hash', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('device_session_key', models.CharField(blank=True, max_length=80)),
                ('device_user_agent', models.TextField(blank=True)),
                ('device_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ticket_scanner_passes', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_scanner_passes', to='events.event')),
            ],
            options={
                'ordering': ('gate_name', 'staff_label', '-created_at'),
            },
        ),
        migrations.AddField(
            model_name='ticketcheckin',
            name='scanner_gate_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='ticketcheckin',
            name='scanner_pass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='ticketing.ticketscannerpass'),
        ),
        migrations.AddField(
            model_name='ticketcheckin',
            name='scanner_staff_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='ticketscannerpass',
            index=models.Index(fields=['event', 'status', 'expires_at'], name='scanner_event_status_exp'),
        ),
        migrations.AddIndex(
            model_name='ticketscannerpass',
            index=models.Index(fields=['token', 'status'], name='scanner_token_status'),
        ),
        migrations.AddIndex(
            model_name='ticketcheckin',
            index=models.Index(fields=['scanner_pass', '-scanned_at'], name='checkin_pass_scanned'),
        ),
    ]
