# Generated by Django 6.0.4 on 2026-06-07 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_public_code'),
        ('ticketing', '0003_ticketscannerpass_checkin_scanner_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketscannerpass',
            name='allow_provisional_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TicketProvisionalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_attempt_id', models.CharField(max_length=80, unique=True)),
                ('ticket_code', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending sync'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('duplicate_rejected', 'Duplicate rejected'), ('wrong_event_rejected', 'Wrong event rejected'), ('not_found_rejected', 'Not found rejected'), ('inactive_rejected', 'Inactive rejected'), ('unauthorized_rejected', 'Unauthorized rejected')], default='pending', max_length=32)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('gate_name', models.CharField(blank=True, max_length=80)),
                ('staff_label', models.CharField(blank=True, max_length=120)),
                ('device_id', models.CharField(blank=True, max_length=80)),
                ('offline_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('scanner_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('scanner_user_agent', models.TextField(blank=True)),
                ('cached_ticket_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_provisional_entries', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_provisional_entries', to='events.event')),
                ('final_checkin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisional_entries', to='ticketing.ticketcheckin')),
                ('scanner_pass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisional_entries', to='ticketing.ticketscannerpass')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisional_entries', to='ticketing.ticket')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['event', '-created_at'], name='prov_event_created'), models.Index(fields=['scanner_pass', '-created_at'], name='prov_pass_created'), models.Index(fields=['status', 'result'], name='prov_status_result')],
            },
        ),
    ]
