# Generated by Django 6.0.4 on 2026-06-08 08:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_ticketscannerpass_allow_provisional_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpurchase',
            name='buyer_handling_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
