# Generated by Django 6.0.4 on 2026-04-14 00:25

import django.db.models.deletion
import nominees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180)),
                ('code', models.CharField(default=nominees.models.generate_vote_code, editable=False, max_length=12, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='nominees/photos/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominees', to='events.event')),
            ],
            options={
                'ordering': ('display_order', 'name'),
                'constraints': [models.UniqueConstraint(fields=('event', 'slug'), name='unique_nominee_slug_per_event')],
            },
        ),
    ]
