# Generated by Django 6.0.4 on 2026-06-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominee',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='nominee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
