# Generated by Django 6.0.4 on 2026-06-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_contactinquiry_contact_inquiry_created'),
        ('nominees', '0003_competitioncategory_nominationsubmission_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='nominationsubmission',
            index=models.Index(fields=['email'], name='nomsub_email'),
        ),
        migrations.AddIndex(
            model_name='nominationsubmission',
            index=models.Index(fields=['phone_number'], name='nomsub_phone'),
        ),
    ]
