# Generated by Django 6.0.4 on 2026-04-14 00:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('nominees', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('payment_reference', models.CharField(max_length=100, unique=True)),
                ('voter_name', models.CharField(blank=True, max_length=120)),
                ('voter_email', models.EmailField(blank=True, max_length=254)),
                ('voter_phone', models.CharField(blank=True, max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vote_purchases', to='events.event')),
                ('nominee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vote_purchases', to='nominees.nominee')),
                ('payment_attempt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vote_purchase', to='payments.paymentattempt')),
            ],
            options={
                'ordering': ('-paid_at',),
            },
        ),
    ]
