# Generated by Django 6.0.4 on 2026-06-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_evt_owner_kind_stat_start_and_more'),
        ('nominees', '0001_initial'),
        ('payments', '0003_paymentattempt_pay_event_status_init_and_more'),
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='votepurchase',
            index=models.Index(fields=['event', '-paid_at'], name='vote_event_paid_at'),
        ),
        migrations.AddIndex(
            model_name='votepurchase',
            index=models.Index(fields=['nominee', '-paid_at'], name='vote_nominee_paid_at'),
        ),
    ]
