# Generated by Django 6.0.4 on 2026-06-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_votepurchase_vote_event_paid_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='USSDSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=32)),
                ('user_id', models.CharField(blank=True, max_length=100)),
                ('current_state', models.CharField(default='INITIATE', max_length=50)),
                ('nominee_id', models.IntegerField(blank=True, null=True)),
                ('votes_count', models.IntegerField(blank=True, null=True)),
                ('amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
