# Generated by Django 6.0.4 on 2026-06-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_ussdsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='ussdsession',
            name='event_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ussdsession',
            name='ticket_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ussdsession',
            name='ticket_type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
