# Generated by Codex on 2026-06-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0004_ussdsession_event_id_ussdsession_ticket_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ussdsession',
            name='purchase_for',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='ussdsession',
            name='recipient_phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
