# Generated by Django 6.0.4 on 2026-06-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0005_ussdsession_purchase_for_and_recipient_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ussdsession',
            name='current_state',
            field=models.CharField(choices=[('INITIATE', 'Initiate'), ('ENTER_NOMINEE_CODE', 'Enter Nominee Code'), ('ENTER_TICKET_EVENT_CODE', 'Enter Ticket Event Code'), ('SELECT_BUNDLE', 'Select Bundle'), ('SELECT_TICKET_PURCHASE_FOR', 'Select Ticket Purchase For'), ('ENTER_RECIPIENT_PHONE', 'Enter Recipient Phone'), ('CONFIRM_RECIPIENT_PHONE', 'Confirm Recipient Phone'), ('SELECT_TICKET_TYPE', 'Select Ticket Type'), ('ENTER_TICKET_QUANTITY', 'Enter Ticket Quantity'), ('ENTER_VOTES', 'Enter Votes'), ('ENTER_CUSTOM_VOTES', 'Enter Custom Votes'), ('CONFIRM_PAYMENT', 'Confirm Payment'), ('CONFIRM_TICKET_PAYMENT', 'Confirm Ticket Payment')], default='INITIATE', max_length=50),
        ),
        migrations.AlterField(
            model_name='ussdsession',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='ussdsession',
            name='ticket_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ussdsession',
            name='votes_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
