# Generated by Django 6.0.4 on 2026-06-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_contactinquiry_contact_inquiry_created'),
        ('nominees', '0004_nominationsubmission_nomsub_email_and_more'),
        ('payments', '0004_paymentattempt_platform_commission_percent'),
        ('votes', '0006_alter_ussdsession_current_state_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='votepurchase',
            index=models.Index(fields=['event', 'nominee', '-paid_at'], name='vote_event_nominee_paid'),
        ),
    ]
