# Generated by Django 6.0.4 on 2026-06-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
        ('events', '0005_event_evt_owner_kind_stat_start_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ballotselection',
            index=models.Index(fields=['position', 'candidate'], name='ballot_sel_pos_candidate'),
        ),
        migrations.AddIndex(
            model_name='electioncredential',
            index=models.Index(fields=['event', 'status', '-created_at'], name='cred_event_status_created'),
        ),
        migrations.AddIndex(
            model_name='electionvoter',
            index=models.Index(fields=['event', 'status', 'external_id'], name='voter_event_status_ext'),
        ),
    ]
