# Generated by Django 6.0.4 on 2026-06-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_ballotselection_ballot_sel_pos_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electioncandidate',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='electioncandidate',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
