# Generated by Django 6.0.4 on 2026-06-07 18:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_electioncandidate_email_electioncandidate_phone'),
        ('events', '0015_contactinquiry_contact_inquiry_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='electionauditlog',
            index=models.Index(fields=['event', '-created_at'], name='auditlog_event_created'),
        ),
    ]
