# Generated by Django 6.0.4 on 2026-05-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_number_user_sms_opt_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organizer_type',
            field=models.CharField(choices=[('student', 'Student'), ('company', 'Company / Organization'), ('individual', 'Individual')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_source',
            field=models.CharField(blank=True, help_text='Where did you hear about VoteCentral?', max_length=100),
        ),
    ]
