# Generated by Django 6.0.4 on 2026-05-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_organizer_type_user_referral_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Organizer avatar image', null=True, upload_to='avatars/'),
        ),
    ]
