# Generated by Django 6.0.4 on 2026-06-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_opt_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='marketing_opt_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sms_opt_in',
            field=models.BooleanField(default=True),
        ),
    ]
