# Generated by Django 6.0.4 on 2026-06-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_email_opt_in_user_marketing_opt_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_source',
            field=models.CharField(blank=True, help_text='Where did you hear about Vootely?', max_length=100),
        ),
    ]
