# Generated by Django 6.0.4 on 2026-06-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_referral_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_seen_onboarding_tour',
            field=models.BooleanField(default=False, help_text='Designates whether the user has completed the interactive onboarding tour.'),
        ),
    ]
