# Generated by Django 6.0.4 on 2026-04-17 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='kind',
            field=models.CharField(choices=[('organizer_sale_credit', 'Organizer Sale Credit'), ('platform_fee_credit', 'Platform Fee Credit'), ('gateway_settlement_debit', 'Gateway Settlement Debit'), ('organizer_withdrawal_debit', 'Organizer Withdrawal Debit'), ('platform_payout_credit', 'Platform Payout Credit'), ('adjustment', 'Adjustment')], max_length=40),
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('payout_name', models.CharField(max_length=120)),
                ('bank_name', models.CharField(max_length=120)),
                ('bank_account_number', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('review_notes', models.TextField(blank=True)),
                ('payout_reference', models.CharField(blank=True, max_length=100)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_withdrawal_requests', to=settings.AUTH_USER_MODEL)),
                ('wallet_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_requests', to='wallets.walletaccount')),
            ],
            options={
                'ordering': ('-requested_at',),
            },
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='withdrawal_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_transaction', to='wallets.withdrawalrequest'),
        ),
    ]
