# Generated by Django 6.0.4 on 2026-04-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_alter_ledgerentry_kind_withdrawalrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='bank_code',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payout_type',
            field=models.CharField(choices=[('bank', 'Bank Account'), ('mobile_money', 'Mobile Money')], default='bank', max_length=16),
        ),
    ]
