# Generated by Django 6.0.4 on 2026-05-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_withdrawalrequest_bank_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='bank_code',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='payout_type',
            field=models.CharField(blank=True, choices=[('bank', 'Bank Account'), ('mobile_money', 'Mobile Money')], default='bank', max_length=16),
        ),
    ]
