# Generated by Django 6.0.4 on 2026-06-01 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_alter_withdrawalrequest_bank_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['account', 'kind', '-created_at'], name='ledger_acct_kind_created'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['transaction', 'kind'], name='ledger_tx_kind'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['organizer', 'status', '-requested_at'], name='wd_org_status_request'),
        ),
    ]
