# Generated by Django 6.0.4 on 2026-06-06 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
        ('wallets', '0005_ledgerentry_ledger_acct_kind_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgertransaction',
            name='ticket_purchase',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_transaction', to='ticketing.ticketpurchase'),
        ),
    ]
