# Generated by Django 6.0.4 on 2026-06-07 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_ledgertransaction_ticket_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='wallets.ledgertransaction'),
        ),
    ]
