from django.urls import path

from accounts.views import (
    DashboardNotificationSettingsView,
    DashboardProfileView,
    DashboardNotificationsView,
    MarkAllNotificationsReadView,
    MarkNotificationReadView,
    CompleteOnboardingView,
)
from nominees.views import (
    DashboardCategoryCreateView,
    DashboardCategoryDeleteView,
    DashboardCategoryUpdateView,
    DashboardNominationReviewView,
    DashboardNominationSubmissionListView,
    DashboardNomineeCreateView,
    DashboardNomineeDeleteView,
    DashboardNomineeUpdateView,
)
from wallets.views import (
    BankListPartialView,
    DashboardRevenueView,
    DashboardWithdrawalsView,
    RequestOTPView,
    ResolveAccountView,
    DashboardAnalyticsView,
    DashboardAnalyticsNomineesFragmentView,
)
from ticketing.views import (
    DashboardTicketAttendeesView,
    DashboardTicketCheckInLaunchView,
    DashboardTicketCheckInProvisionalSyncView,
    DashboardTicketCheckInScanView,
    DashboardTicketCheckInView,
    DashboardTicketScannerPassActionView,
    DashboardTicketScannerPassListView,
    DashboardTicketSalesView,
    DashboardTicketTypeCreateView,
    DashboardTicketTypeDeleteView,
    DashboardTicketTypeUpdateView,
    DashboardTicketedEventActionView,
    DashboardTicketedEventCreateView,
    DashboardTicketedEventDetailView,
    DashboardTicketedEventUpdateView,
    DashboardTicketedEventsListView,
)
from elections.views import (
    DashboardElectionActionView,
    DashboardElectionCandidatesView,
    DashboardElectionCreateView,
    DashboardElectionCredentialsView,
    DashboardElectionDetailView,
    DashboardElectionInvoiceView,
    DashboardElectionPositionsView,
    DashboardElectionRosterView,
    DashboardElectionUpdateView,
    DashboardElectionPositionUpdateView,
    DashboardElectionPositionDeleteView,
    DashboardElectionCandidateUpdateView,
    DashboardElectionCandidateDeleteView,
)

from .views import (
    DashboardEventActionView,
    DashboardEventCreateView,
    DashboardEventDetailView,
    DashboardEventUpdateView,
    DashboardHomeView,
    DashboardSearchView,
    DashboardCompetitionsListView,
    DashboardElectionsListView,
    DashboardVoteBundleCreateView,
    DashboardVoteBundleDeleteView,
)

app_name = 'dashboard'

urlpatterns = [
    path('', DashboardHomeView.as_view(), name='home'),
    path('competitions/', DashboardCompetitionsListView.as_view(), name='competitions'),
    path('tickets/', DashboardTicketedEventsListView.as_view(), name='tickets'),
    path('elections/', DashboardElectionsListView.as_view(), name='elections'),
    path('my-events/', DashboardCompetitionsListView.as_view(), name='my_events'),
    path('profile/', DashboardProfileView.as_view(), name='profile'),
    path('search/', DashboardSearchView.as_view(), name='search'),
    path('analytics/', DashboardAnalyticsView.as_view(), name='analytics'),
    path(
        'analytics/fragments/nominees/',
        DashboardAnalyticsNomineesFragmentView.as_view(),
        name='analytics_nominees_fragment',
    ),
    path('notifications/', DashboardNotificationsView.as_view(), name='notifications'),
    path('notifications/read-all/', MarkAllNotificationsReadView.as_view(), name='mark_all_read'),
    path('notifications/<int:pk>/read/', MarkNotificationReadView.as_view(), name='mark_read'),
    path('revenue/', DashboardRevenueView.as_view(), name='revenue'),
    path('withdrawals/', DashboardWithdrawalsView.as_view(), name='withdrawals'),
    path('withdrawals/resolve-account/', ResolveAccountView.as_view(), name='resolve_account'),
    path('withdrawals/bank-list/', BankListPartialView.as_view(), name='bank_list'),
    path('withdrawals/request-otp/', RequestOTPView.as_view(), name='request_otp'),
    path(
        'settings/notifications/',
        DashboardNotificationSettingsView.as_view(),
        name='notification_settings',
    ),
    path(
        'accounts/complete-onboarding/',
        CompleteOnboardingView.as_view(),
        name='complete_onboarding',
    ),
    path('events/new/', DashboardEventCreateView.as_view(), name='event_create'),
    path('tickets/new/', DashboardTicketedEventCreateView.as_view(), name='ticketed_event_create'),
    path('tickets/check-in/', DashboardTicketCheckInLaunchView.as_view(), name='ticket_check_in_launch'),
    path('tickets/<slug:slug>/', DashboardTicketedEventDetailView.as_view(), name='ticketed_event_detail'),
    path('tickets/<slug:slug>/edit/', DashboardTicketedEventUpdateView.as_view(), name='ticketed_event_edit'),
    path(
        'tickets/<slug:slug>/actions/<str:action>/',
        DashboardTicketedEventActionView.as_view(),
        name='ticketed_event_action',
    ),
    path('elections/new/', DashboardElectionCreateView.as_view(), name='election_create'),
    path('elections/<slug:slug>/', DashboardElectionDetailView.as_view(), name='election_detail'),
    path('elections/<slug:slug>/edit/', DashboardElectionUpdateView.as_view(), name='election_edit'),
    path('elections/<slug:slug>/positions/', DashboardElectionPositionsView.as_view(), name='election_positions'),
    path(
        'elections/<slug:slug>/positions/<int:pk>/edit/',
        DashboardElectionPositionUpdateView.as_view(),
        name='election_position_edit',
    ),
    path(
        'elections/<slug:slug>/positions/<int:pk>/delete/',
        DashboardElectionPositionDeleteView.as_view(),
        name='election_position_delete',
    ),
    path('elections/<slug:slug>/candidates/', DashboardElectionCandidatesView.as_view(), name='election_candidates'),
    path(
        'elections/<slug:slug>/candidates/<int:pk>/edit/',
        DashboardElectionCandidateUpdateView.as_view(),
        name='election_candidate_edit',
    ),
    path(
        'elections/<slug:slug>/candidates/<int:pk>/delete/',
        DashboardElectionCandidateDeleteView.as_view(),
        name='election_candidate_delete',
    ),
    path('elections/<slug:slug>/roster/', DashboardElectionRosterView.as_view(), name='election_roster'),
    path('elections/<slug:slug>/invoice/', DashboardElectionInvoiceView.as_view(), name='election_invoice'),
    path('elections/<slug:slug>/credentials/', DashboardElectionCredentialsView.as_view(), name='election_credentials'),
    path(
        'elections/<slug:slug>/actions/<str:action>/',
        DashboardElectionActionView.as_view(),
        name='election_action',
    ),
    path('events/<slug:slug>/', DashboardEventDetailView.as_view(), name='event_detail'),
    path('events/<slug:slug>/edit/', DashboardEventUpdateView.as_view(), name='event_edit'),
    path(
        'events/<slug:slug>/actions/<str:action>/',
        DashboardEventActionView.as_view(),
        name='event_action',
    ),
    path(
        'events/<slug:event_slug>/nominees/new/',
        DashboardNomineeCreateView.as_view(),
        name='nominee_create',
    ),
    path(
        'events/<slug:event_slug>/categories/new/',
        DashboardCategoryCreateView.as_view(),
        name='category_create',
    ),
    path(
        'events/<slug:event_slug>/categories/<slug:category_slug>/edit/',
        DashboardCategoryUpdateView.as_view(),
        name='category_edit',
    ),
    path(
        'events/<slug:event_slug>/categories/<slug:category_slug>/delete/',
        DashboardCategoryDeleteView.as_view(),
        name='category_delete',
    ),
    path(
        'events/<slug:event_slug>/nominees/<slug:slug>/edit/',
        DashboardNomineeUpdateView.as_view(),
        name='nominee_edit',
    ),
    path(
        'events/<slug:event_slug>/nominees/<slug:slug>/delete/',
        DashboardNomineeDeleteView.as_view(),
        name='nominee_delete',
    ),
    path(
        'events/<slug:event_slug>/nominations/',
        DashboardNominationSubmissionListView.as_view(),
        name='nomination_queue',
    ),
    path(
        'events/<slug:event_slug>/nominations/<int:pk>/',
        DashboardNominationReviewView.as_view(),
        name='nomination_review',
    ),
    path(
        'events/<slug:event_slug>/bundles/new/',
        DashboardVoteBundleCreateView.as_view(),
        name='vote_bundle_create',
    ),
    path(
        'events/<slug:event_slug>/bundles/<int:pk>/delete/',
        DashboardVoteBundleDeleteView.as_view(),
        name='vote_bundle_delete',
    ),
    path(
        'events/<slug:event_slug>/ticket-types/new/',
        DashboardTicketTypeCreateView.as_view(),
        name='ticket_type_create',
    ),
    path(
        'events/<slug:event_slug>/ticket-types/<int:pk>/edit/',
        DashboardTicketTypeUpdateView.as_view(),
        name='ticket_type_edit',
    ),
    path(
        'events/<slug:event_slug>/ticket-types/<int:pk>/delete/',
        DashboardTicketTypeDeleteView.as_view(),
        name='ticket_type_delete',
    ),
    path(
        'events/<slug:event_slug>/ticket-sales/',
        DashboardTicketSalesView.as_view(),
        name='ticket_sales',
    ),
    path(
        'events/<slug:event_slug>/attendees/',
        DashboardTicketAttendeesView.as_view(),
        name='ticket_attendees',
    ),
    path(
        'events/<slug:event_slug>/check-in/',
        DashboardTicketCheckInView.as_view(),
        name='ticket_check_in',
    ),
    path(
        'events/<slug:event_slug>/check-in/access/',
        DashboardTicketScannerPassListView.as_view(),
        name='ticket_scanner_passes',
    ),
    path(
        'events/<slug:event_slug>/check-in/access/<int:pk>/<str:action>/',
        DashboardTicketScannerPassActionView.as_view(),
        name='ticket_scanner_pass_action',
    ),
    path(
        'events/<slug:event_slug>/check-in/scan/',
        DashboardTicketCheckInScanView.as_view(),
        name='ticket_check_in_scan',
    ),
    path(
        'events/<slug:event_slug>/check-in/provisional-sync/',
        DashboardTicketCheckInProvisionalSyncView.as_view(),
        name='ticket_check_in_provisional_sync',
    ),
]
