# Generated by Django 6.0.4 on 2026-04-18 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('payments', '0002_paymentattempt_callback_received_at_and_more'),
        ('wallets', '0002_alter_ledgerentry_kind_withdrawalrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email')], default='email', max_length=16)),
                ('event_type', models.CharField(choices=[('payment_confirmed', 'Payment Confirmed'), ('payment_failed', 'Payment Failed'), ('payment_cancelled', 'Payment Cancelled'), ('withdrawal_requested', 'Withdrawal Requested'), ('withdrawal_approved', 'Withdrawal Approved'), ('withdrawal_processing', 'Withdrawal Processing'), ('withdrawal_completed', 'Withdrawal Completed'), ('withdrawal_rejected', 'Withdrawal Rejected'), ('withdrawal_review_required', 'Withdrawal Review Required'), ('event_published', 'Event Published'), ('event_closed', 'Event Closed'), ('event_starting_soon', 'Event Starting Soon'), ('event_ending_soon', 'Event Ending Soon')], max_length=40)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=120)),
                ('subject', models.CharField(max_length=255)),
                ('body_text', models.TextField()),
                ('body_html', models.TextField(blank=True)),
                ('dedupe_key', models.CharField(max_length=255, unique=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=120)),
                ('failure_reason', models.TextField(blank=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='events.event')),
                ('payment_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='payments.paymentattempt')),
                ('withdrawal_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='wallets.withdrawalrequest')),
            ],
            options={
                'ordering': ('-queued_at',),
            },
        ),
    ]
