# Generated by Django 6.0.4 on 2026-06-01 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_evt_owner_kind_stat_start_and_more'),
        ('nominees', '0001_initial'),
        ('notifications', '0003_inappnotification'),
        ('payments', '0002_paymentattempt_callback_received_at_and_more'),
        ('wallets', '0005_ledgerentry_ledger_acct_kind_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inappnotification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='inapp_user_read_created'),
        ),
    ]
