# Generated by Django 6.0.4 on 2026-06-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_inappnotification_inapp_user_read_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('payment_confirmed', 'Payment Confirmed'), ('payment_failed', 'Payment Failed'), ('payment_cancelled', 'Payment Cancelled'), ('withdrawal_requested', 'Withdrawal Requested'), ('withdrawal_approved', 'Withdrawal Approved'), ('withdrawal_processing', 'Withdrawal Processing'), ('withdrawal_completed', 'Withdrawal Completed'), ('withdrawal_rejected', 'Withdrawal Rejected'), ('withdrawal_review_required', 'Withdrawal Review Required'), ('event_published', 'Event Published'), ('event_closed', 'Event Closed'), ('event_starting_soon', 'Event Starting Soon'), ('event_ending_soon', 'Event Ending Soon'), ('organizer_welcome', 'Welcome Organizer'), ('nominee_goes_live', 'Nominee Goes Live'), ('nominee_event_closed', 'Nominee Event Closed'), ('candidate_confirmed', 'Candidate Confirmed'), ('candidate_election_closed', 'Candidate Election Closed'), ('voter_credentials', 'Voter Credentials'), ('voter_election_closed', 'Voter Election Closed'), ('voter_ballot_cast', 'Voter Ballot Cast')], max_length=40),
        ),
    ]
