# Generated by Django 6.0.4 on 2026-06-06 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_alter_notification_event_type'),
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='ticket_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='ticketing.ticketpurchase'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('payment_confirmed', 'Payment Confirmed'), ('payment_failed', 'Payment Failed'), ('payment_cancelled', 'Payment Cancelled'), ('withdrawal_requested', 'Withdrawal Requested'), ('withdrawal_approved', 'Withdrawal Approved'), ('withdrawal_processing', 'Withdrawal Processing'), ('withdrawal_completed', 'Withdrawal Completed'), ('withdrawal_rejected', 'Withdrawal Rejected'), ('withdrawal_review_required', 'Withdrawal Review Required'), ('event_published', 'Event Published'), ('event_closed', 'Event Closed'), ('event_commission_setup_required', 'Event Commission Setup Required'), ('event_starting_soon', 'Event Starting Soon'), ('event_ending_soon', 'Event Ending Soon'), ('organizer_welcome', 'Welcome Organizer'), ('nominee_goes_live', 'Nominee Goes Live'), ('nominee_event_closed', 'Nominee Event Closed'), ('nomination_submitted', 'Nomination Submitted'), ('nomination_approved', 'Nomination Approved'), ('nomination_rejected', 'Nomination Rejected'), ('candidate_confirmed', 'Candidate Confirmed'), ('candidate_election_closed', 'Candidate Election Closed'), ('voter_credentials', 'Voter Credentials'), ('voter_election_closed', 'Voter Election Closed'), ('voter_ballot_cast', 'Voter Ballot Cast'), ('voter_turnout_reminder', 'Voter Turnout Reminder'), ('ticket_purchased', 'Ticket Purchased'), ('ticket_payment_failed', 'Ticket Payment Failed'), ('ticket_checked_in', 'Ticket Checked In')], max_length=40),
        ),
    ]
