# Generated by Django 6.0.4 on 2026-06-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_contactinquiry_contact_inquiry_created'),
        ('notifications', '0009_notification_ticket_purchase_and_more'),
        ('payments', '0004_paymentattempt_platform_commission_percent'),
        ('ticketing', '0004_ticketscannerpass_allow_provisional_entry_and_more'),
        ('wallets', '0007_alter_ledgerentry_transaction'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'queued_at'], name='notif_status_queued'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['channel', 'status'], name='notif_channel_status'),
        ),
    ]
